name: Daily Build - MI
on:
  schedule:
    - cron:  '30 13 * * *'

jobs:
  Release:
    name: Release VSIX
    timeout-minutes: 45
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.BALLERINA_BOT_TOKEN }}
          fetch-depth: 2
          ref: mi-ext

      - name: Build
        uses: ./.github/actions/build
        with:
          mi: true
          API_CHAT_API_KEY: ${{ secrets.API_CHAT_API_KEY }}  
          token: ${{ secrets.PUBLISH_PAT }}

      - name: Notification - MI
        uses: ./.github/actions/dailyBuildNotification
        with:
          title: Micro Integrator
          fileName: micro-integrator
          chatAPI: ${{ secrets.MI_TEAM_CHAT_API }}
