# Test build against released Ballerina distribution
name: Draft A Release

on:
  workflow_dispatch:
    inputs:
      plugin_version:
        description: VSIX Release Version
        required: true
        default: 2.0.0-Preview5-SNAPSHOT
      tag:
        description: Release Tag
        required: true
        default: vswan-lake-preview5-snapshot
      vsix_version:
        description: Name of VSIX Asset
        required: true
        default: swan-lake-preview5-snapshot
      bal_dist_version:
        description: Version of Ballerina distribution
        required: true
        default: swan-lake-preview5
    branches: [master]

jobs:
  build:
    name: Upload VSIX as release assets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build project
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Install java 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Download ballerina distribution
        uses: wei/wget@v1
        with:
          args: http://dist-dev.ballerina.io/downloads/${{ github.event.inputs.bal_dist_version }}/ballerina-${{ github.event.inputs.bal_dist_version }}.zip
      - run: mkdir extractedDistribution
      - name: Unzip ballerina distribution
        uses: TonyBogdanov/zip@1.0
        with:
          args: unzip -qq ./ballerina-${{ github.event.inputs.bal_dist_version }}.zip -d ./extractedDistribution
      - run: rm ballerina-${{ github.event.inputs.bal_dist_version }}.zip
      - run: npm ci
      - name: Build repository with tests
        uses: GabrielBB/xvfb-action@v1.0
        with:
          run: ./gradlew clean build
      - name: Create Release Draft
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.BALLERINA_BOT_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.tag }}
          release_name: Release ${{ github.event.inputs.vsix_version }}
          draft: true
          prerelease: true
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.BALLERINA_BOT_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./ballerina-${{ github.event.inputs.plugin_version }}.vsix
          asset_name: ballerina-${{ github.event.inputs.vsix_version }}.vsix
          asset_content_type: application/octet-stream
