# Create a plugin release upon a new tag creation without running tests.
# This release honors the package-lock files without updating the npm dependencies.
name: Release for a new tag

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Create a release for VS Code extension without running tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Log release tag
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}
      - name: Build project
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install java 11
        uses: actions/setup-java@v1
        with:
          java-version: "11"
      - name: Build repository without tests
        run: sudo apt-get install xvfb && xvfb-run --auto-servernum ./gradlew clean build -x test
        env:
          NPM_ACCESS_TOKEN: ${{ secrets.PUBLISH_PAT }}
          IS_RELEASE: ${{ true }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      - run: find . -type f -name '*.vsix' -exec sh -c 'x="{}"; mv "$x" ballerina.vsix' \;
      - name: Create a release in wso2/ballerina-plugin-vscode repo
        run: |
          createResponse=`curl -X POST  -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization:token ${{ secrets.PUBLISH_PAT }}" -d '{"tag_name":"${{ env.RELEASE_VERSION }}", \
          "draft":false, "name": "Release ${{ env.RELEASE_VERSION }}", "prerelease":true}' \
          https://api.github.com/repos/wso2/ballerina-plugin-vscode/releases` \
           && id=`echo "$createResponse" | sed -n -e 's/"id":\ \([0-9]\+\),/\1/p' | head -n 1 | sed 's/[[:blank:]]//g'` && \
           uploadResponse=`curl -X POST -H "Authorization:token ${{ secrets.PUBLISH_PAT }}" -H "Content-Type:application/octet-stream" \
            --data-binary @ballerina.vsix \
            https://uploads.github.com/repos/wso2/ballerina-plugin-vscode/releases/$id/assets?name=ballerina.vsix`
